project:
  type: book
  preview:
    port: 4200
    browser: false
  pre-render:
  # - R/installpkgs.R
  - R/makeChapterRscripts.R
  post-render:
  - R/makePkgList.R

book:
  title: "Robust and nimble scientific workflows, using SpaDES"
  author:
    - "Eliot McIntire"
    - "Ceres Barros"
  date: last-modified
  cover-image: assets/logo/predictive_ecology_logo.png
  favicon:  assets/logo/favicon-16x16.png
  site-url: https://predictiveecology.org/

  navbar:
    logo: "assets/logo/favicon-196x196.png"
    search: true
    right:
      - text: "News"
        href: ../../index.html
      - text: "About"
        href: ../../about.html
      - text: "Projects"
        href: ../../Projects.html
      - text: "SpaDES"
        href: ../../SpaDES.html
      - text: Workshops
        menu:
          - text: "Workshops"
            href: ../../Workshops.html
          - text: "June 2024 Workshop Agenda"
            href: ../../workshops/June-2024-SpaDES-workshop.html
          - text: "November 2024 Workshop Agenda"
            href: ../../workshops/Nov-2024-SpaDES-workshop.html
      - text: "Training"
        menu:
          - text: "Training Book"
            href: index.html
          - text: "Other training resources"
            href: ../otherTraining.html
      - text: "Manuals"
        href: ../../Manuals.html
      - text: "Publications"
        href: ../../publications.html
      - text: "Presentations"
        href: ../../presentations.html
      - icon: github
        href: https://github.com/PredictiveEcology
      - icon: twitter
        href: https://twitter.com/PredictiveEcol

  chapters:
    - index.qmd
    - intro.qmd
    - part: settingUp.qmd
      chapters:
      - installRandSpatialPkgs.qmd
      - PackagesForBook.qmd
      - TroubleshootingPackageInstallation.qmd
    - part: SpaDESbasics.qmd
      chapters:
      - NewModuleIntro.qmd
      - MetaDataAndModuleFiles.qmd
      - ModuleInputs.qmd
      - simList.qmd
      - ModulesAndEvents.qmd
      - Scheduling.qmd
    - part: ContinuousWorkflows.qmd
      chapters:
      - Caching.qmd
      - prepInputs.qmd
      - debugging.qmd
    - part: setupProject.qmd
      chapters:
      - workflowSimple2.qmd
      - LandRDemo_coreVeg.qmd
      - ForestsAndFire.qmd
      #- castorExample.qmd
      - spadesCBMDemo.qmd
    - bestPractices.qmd
    - references.qmd

bibliography: references/references.bib

format:
  html:
    theme:
      light: flatly
      dark: darkly
    grid:
      sidebar-width: 350px
    number-sections: true
    fig-cap-location: bottom
    tbl-cap-location: top
    title-block-banner: false
    title-block-categories: false
    code-fold: show
    code-overflow: scroll
    code-copy: true
    css: assets/css/main.scss
    smooth-scroll: true
    link-external-newwindow: true

execute:
  freeze: auto
  cache: true

editor:
  mode: source
  markdown:
    wrap: 72
    references:
      location: document

